In [ ]:
a, b = 5, 10
a, b = b, a   # tuple unpacking swap - no temp variable needed
print("Q1:", a, b)  # 10 5


Q1: 10 5


In [ ]:
#Q2
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True
print (is_prime(5))

True


In [ ]:
def fibonacci(n):
    seq = []
    x, y = 0, 1
    for _ in range(n):
        seq.append(x)
        x, y = y, x + y
    return seq

print("Q3:", fibonacci(10))


Q3: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [ ]:
def remove_duplicates(lst):
    seen = set()
    result = []
    for item in lst:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result

print("Q4:", remove_duplicates([1, 2, 2, 3, 1, 4, 3]))  # [1, 2, 3, 4]



Q4: [1, 2, 3, 4]


In [ ]:
def count_chars(s):
    vowels = consonants = digits = spaces = 0
    for ch in s:
        if ch.isalpha():
            if ch.lower() in "aeiou":
                vowels += 1
            else:
                consonants += 1
        elif ch.isdigit():
            digits += 1
        elif ch.isspace():
            spaces += 1
    return vowels, consonants, digits, spaces

print("Q5:", count_chars("Hello World 123"))


Q5: (3, 7, 3, 2)


In [ ]:
def multiply(*args):
    result = 1
    for num in args:
        result *= num
    return result

print("Q6:", multiply(2, 3, 4))

Q6: 24


In [ ]:
text = "banana"
freq = {ch: text.count(ch) for ch in text}
print("Q7:", freq)


Q7: {'b': 1, 'a': 3, 'n': 2}


In [ ]:
employees = [
    {"name": "Ali", "department": "Sales", "salary": 55000},
    {"name": "Sara", "department": "IT", "salary": 62000},
    {"name": "Omar", "department": "Sales", "salary": 48000},
]
top_employee = max(employees, key=lambda e: e["salary"])
print("Q8:", top_employee)


Q8: {'name': 'Sara', 'department': 'IT', 'salary': 62000}


In [ ]:
def is_palindrome(s):
    cleaned = s.lower().replace(" ", "")
    return cleaned == cleaned[::-1]

print("Q9:", is_palindrome("Nurses Run"))

Q9: True


In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
odd_numbers = list(filter(lambda x: x % 2 != 0, numbers))
print("Q10:", odd_numbers)  # [1, 3, 5, 7, 9]

Q10: [1, 3, 5, 7, 9]


In [4]:
#Section B
import numpy as np

In [ ]:
arr11 = np.arange(1, 31).reshape(5, 6)
print("Q11:\n", arr11)

Q11:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [ ]:
arr12 = np.eye(6)
np.fill_diagonal(arr12, [1, 2, 3, 4, 5, 6])
print("Q12:\n", arr12)


Q12:
 [[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


In [ ]:
np.random.seed(42)
arr13 = np.random.randint(1, 101, 25)
print("Q13:", "sum=", arr13.sum(), "mean=", arr13.mean(), "std=", arr13.std())


Q13: sum= 1262 mean= 50.48 std= 30.899993527507412


In [ ]:
arr14 = np.arange(1, 17).reshape(4, 4)
diagonal = np.diag(arr14)
print("Q14:", diagonal, "sum=", diagonal.sum())


Q14: [ 1  6 11 16] sum= 34


In [ ]:
A15 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B15 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print("Q15 elementwise (*):\n", A15 * B15)
print("Q15 matrix mult (@):\n", A15 @ B15)


Q15 elementwise (*):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Q15 matrix mult (@):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
np.random.seed(1)
temps = np.random.uniform(20, 45, 30)  # 30 daily temperatures
hot_days = temps[temps > 35]
print("Q16: hot days count =", len(hot_days))

Q16: hot days count = 10


In [ ]:
arr17 = np.array([10, 20, 30, 40, 50])
normalized = (arr17 - arr17.min()) / (arr17.max() - arr17.min())
print("Q17:", normalized)

Q17: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
marks18 = np.array([
    [80, 90, 70],
    [60, 75, 85],
    [90, 95, 100],
    [55, 65, 60],
    [72, 88, 91],
])
totals = marks18.sum(axis=1)
averages = marks18.mean(axis=1)
print("Q18 totals:", totals)
print("Q18 averages:", averages)


Q18 totals: [240 220 285 180 251]
Q18 averages: [80.         73.33333333 95.         60.         83.66666667]


In [ ]:
arr19 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
result19 = np.where(arr19 % 2 == 0, -1, arr19)
print("Q19:", result19)


Q19: [ 1 -1  3 -1  5 -1  7 -1]


In [ ]:
arr20 = np.arange(1, 17).reshape(4, 4).astype(float)
arr20 += np.eye(4)  # nudge so it's invertible (raw 1-16 matrix is singular)
det20 = np.linalg.det(arr20)
print("Q20 transpose:\n", arr20.T)
print("Q20 determinant:", det20)
if abs(det20) > 1e-10:
    print("Q20 inverse:\n", np.linalg.inv(arr20))
else:
    print("Q20: matrix is singular, no inverse")



Q20 transpose:
 [[ 2.  5.  9. 13.]
 [ 2.  7. 10. 14.]
 [ 3.  7. 12. 15.]
 [ 4.  8. 12. 17.]]
Q20 determinant: -44.99999999999996
Q20 inverse:
 [[-2.22222222e-01 -6.66666667e-01 -1.11111111e-01  4.44444444e-01]
 [-6.00000000e-01  6.00000000e-01 -2.00000000e-01  1.37456184e-16]
 [ 2.22222222e-02 -1.33333333e-01  7.11111111e-01 -4.44444444e-01]
 [ 6.44444444e-01  1.33333333e-01 -3.77777778e-01  1.11111111e-01]]


In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
manual_dot = 0
for i in range(len(v1)):
    manual_dot += v1[i] * v2[i]
print("Q21: manual =", manual_dot, "np.dot =", np.dot(v1, v2))


Q21: manual = 32 np.dot = 32


In [ ]:
user_numbers = [23, 5, 67, 12, 89, 34, 1, 45, 78, 10]  # simulate 10 user inputs
arr22 = np.array(user_numbers)
sorted_arr22 = np.sort(arr22)
print("Q22 sorted:", sorted_arr22, "median:", np.median(arr22))


Q22 sorted: [ 1  5 10 12 23 34 45 67 78 89] median: 28.5


In [ ]:
arr23 = np.arange(1, 13).reshape(3, 4)
selected = arr23[np.ix_([0, 2], [1, 3])]
print("Q23:\n", selected)


Q23:
 [[ 2  4]
 [10 12]]


In [5]:
def is_symmetric(matrix):
    return np.array_equal(matrix, matrix.T)

is_symmatrix = np.array([[1, 2, 3], [2, 5, 6], [3, 6, 9]])
non_sym_matrix = np.array([[1, 2], [3, 4]])
print("Q24:", is_symmetric(is_symmatrix), is_symmetric(non_sym_matrix))


Q24: True False


In [6]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
m3 = np.array([[9, 10], [11, 12]])
v_stacked = np.vstack([m1, m2, m3])
h_stacked = np.hstack([m1, m2, m3])
print("Q25 vstack shape:", v_stacked.shape)  # (6, 2) - stacks rows
print("Q25 hstack shape:", h_stacked.shape)  # (2, 6) - stacks columns

Q25 vstack shape: (6, 2)
Q25 hstack shape: (2, 6)


In [7]:
import pandas as pd
import matplotlib
matplotlib.use("Agg")  # no display needed - save straight to file
import matplotlib.pyplot as plt

In [8]:
np.random.seed(0)
days = np.arange(1, 31)
temps26 = np.random.uniform(20, 40, 30)

plt.figure(figsize=(8, 4))
plt.plot(days, temps26, color="tab:blue", marker="o")
plt.title("30-Day Temperature Readings")
plt.xlabel("Day")
plt.ylabel("Temperature (°C)")
plt.grid(True)
plt.savefig("q26_temperature_line.png", dpi=150)
plt.close()


In [9]:
x27 = np.linspace(0, 2 * np.pi, 200)
plt.figure(figsize=(8, 4))
plt.plot(x27, np.sin(x27), label="sin(x)", color="tab:red")
plt.plot(x27, np.cos(x27), label="cos(x)", color="tab:green")
plt.title("sin(x) and cos(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid(True)
plt.savefig("q27_sin_cos.png", dpi=150)
plt.close()

In [10]:
subjects28 = ["Math", "Physics", "Chemistry", "Biology"]
avg_marks28 = [78, 85, 90, 82]
max_idx = avg_marks28.index(max(avg_marks28))
colors28 = ["skyblue"] * len(subjects28)
colors28[max_idx] = "gold"  # highlight the top subject

plt.figure(figsize=(6, 4))
plt.bar(subjects28, avg_marks28, color=colors28)
plt.title("Average Marks by Subject")
plt.xlabel("Subject")
plt.ylabel("Average Marks")
plt.savefig("q28_bar_subjects.png", dpi=150)
plt.close()


In [12]:
np.random.seed(7)
data29 = np.random.randn(500)
plt.figure(figsize=(6, 4))
plt.hist(data29, bins=20, color="lightcoral", edgecolor="black")
plt.axvline(data29.mean(), color="black", linestyle="--", label=f"mean={data29.mean():.2f}")
plt.title("Histogram of 500 Random Numbers")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.legend()
plt.savefig("q29_histogram.png", dpi=150)
plt.close()


In [11]:
df31 = pd.DataFrame({
    "name": ["Pen", "Notebook", "Bag", "Bottle", "Lamp", "Chair"],
    "price": [1.5, 2.0, 25.0, 5.0, 15.0, 45.0],
    "quantity": [100, 60, 10, 40, 8, 5],
})
df31["total"] = df31["price"] * df31["quantity"]
print("Q31:\n", df31)


Q31:
        name  price  quantity  total
0       Pen    1.5       100  150.0
1  Notebook    2.0        60  120.0
2       Bag   25.0        10  250.0
3    Bottle    5.0        40  200.0
4      Lamp   15.0         8  120.0
5     Chair   45.0         5  225.0


In [13]:
df32 = pd.DataFrame({
    "student": [f"S{i}" for i in range(1, 11)],
    "math": [78, 85, 92, 60, 74, 88, 95, 67, 81, 70],
    "science": [82, 79, 88, 65, 70, 91, 89, 72, 84, 68],
    "english": [75, 90, 85, 70, 68, 84, 92, 66, 79, 73],
})
df32["average"] = df32[["math", "science", "english"]].mean(axis=1)
top_performer = df32.loc[df32["average"].idxmax()]
print("Q32:\n", df32)
print("Q32 top performer:\n", top_performer)


Q32:
   student  math  science  english    average
0      S1    78       82       75  78.333333
1      S2    85       79       90  84.666667
2      S3    92       88       85  88.333333
3      S4    60       65       70  65.000000
4      S5    74       70       68  70.666667
5      S6    88       91       84  87.666667
6      S7    95       89       92  92.000000
7      S8    67       72       66  68.333333
8      S9    81       84       79  81.333333
9     S10    70       68       73  70.333333
Q32 top performer:
 student      S7
math         95
science      89
english      92
average    92.0
Name: 6, dtype: object


In [14]:
df33 = pd.DataFrame({
    "date": pd.date_range("2026-01-01", periods=10, freq="D"),
    "sales": [200, 220, 180, 260, 300, 280, 240, 310, 330, 290],
})
df33 = df33.sample(frac=1, random_state=1).sort_values("date")  # shuffle then re-sort to prove sorting works
ax33 = df33.plot(x="date", y="sales", kind="line", marker="o", title="Sales Over Time", figsize=(8, 4))
ax33.set_ylabel("Sales")
plt.savefig("q33_sales_over_time.png", dpi=150)
plt.close()

In [15]:
df34 = pd.DataFrame({
    "student": ["A", "B", "C", "D", "E"],
    "score": [88, np.nan, 76, np.nan, 92],
})
df34["score"] = df34["score"].fillna(df34["score"].mean())
print("Q34:\n", df34)
print("Q34 any NaNs remaining?", df34["score"].isna().any())


Q34:
   student      score
0       A  88.000000
1       B  85.333333
2       C  76.000000
3       D  85.333333
4       E  92.000000
Q34 any NaNs remaining? False
